# Generated by Django 4.2.23 on 2025-07-30 10:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=512)),
                ('product_original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_initial_time', models.DateTimeField(auto_now_add=True, help_text='The time when the product is added to stock')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('product_amount', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_badge', models.CharField(max_length=512, null=True)),
                ('location', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
