# Generated by Django 4.2.20 on 2025-07-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=512)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_vendor', models.CharField(max_length=50)),
                ('product_initial_time', models.DateTimeField()),
                ('is_discounted', models.BooleanField(default=False)),
            ],
        ),
    ]
