# Generated by Django 4.2.20 on 2025-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_product_is_discounted_product_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
