# Generated by Django 4.2.20 on 2025-07-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_product_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_initial_time',
            field=models.DateTimeField(help_text='The time when the product is added to stock'),
        ),
    ]
