# Generated by Django 4.2.20 on 2025-07-16 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_product_price_product_product_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_initial_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 8, 31, 27, 544926, tzinfo=datetime.timezone.utc), help_text='The time when the product is added to stock'),
        ),
    ]
