# Generated by Django 4.2.20 on 2025-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_product_product_initial_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_initial_time',
            field=models.DateTimeField(auto_now=True, help_text='The time when the product is added to stock'),
        ),
    ]
