# Generated by Django 4.2.20 on 2025-07-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
