# Generated by Django 4.2.20 on 2025-07-17 05:52

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0015_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=512)),
                ('product_original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_vendor', models.CharField(max_length=50)),
                ('product_initial_time', models.DateTimeField(auto_now=True, help_text='The time when the product is added to stock')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('product_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
