# Generated by Django 4.2.20 on 2025-07-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
