# Generated by Django 4.2.20 on 2025-07-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_initial_time',
            field=models.DateTimeField(auto_now_add=True, help_text='The time when the product is added to stock'),
        ),
    ]
