# Generated by Django 4.2.20 on 2025-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_badge',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
