# Generated by Django 4.2.20 on 2025-07-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_product_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_vendor',
            new_name='user',
        ),
    ]
