# Generated by Django 4.2.20 on 2025-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profilePictures/'),
            preserve_default=False,
        ),
    ]
