# Generated by Django 4.2.20 on 2025-07-18 07:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2025, 7, 18, 7, 58, 52, 973213, tzinfo=datetime.timezone.utc))),
                ('caption', models.CharField(max_length=1024)),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
