# Generated by Django 4.2.20 on 2025-07-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
