# Generated by Django 4.2.20 on 2025-07-18 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.FileField(default=datetime.datetime(2025, 7, 18, 16, 37, 23, 859518, tzinfo=datetime.timezone.utc), upload_to='stories/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
