# Generated by Django 4.2.20 on 2025-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_options_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='stories/%Y/%m/%d/'),
        ),
    ]
