# Generated by Django 4.2.20 on 2025-07-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
