# Generated by Django 4.2.20 on 2025-07-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_remove_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(null=True, upload_to='stories/%Y/%m/%d/'),
        ),
    ]
