# Generated by Django 4.2.20 on 2025-07-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
