# Generated by Django 4.2.20 on 2025-07-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_story_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='upload_date',
            new_name='created_at',
        ),
    ]
